dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.12
- name: ttc-connectors-reward
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: ttc-connectors-ranking
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.4
- name: ttc-connectors-processing
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.2
- name: ttc-connectors-dummytwitter
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.6
