dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: ttc-rb-english-campaign
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.16
- name: ttc-connectors-reward
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: ttc-connectors-ranking
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.5
- name: ttc-connectors-processing
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.3
- name: ttc-connectors-dummytwitter
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.8
- name: rabbitmq
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.8.0
- name: postgresql
  repository: https://kubernetes-charts.storage.googleapis.com
  version: 0.11.0
